In [1]:
# 1-D array

import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [19]:
# n-D array

import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [20]:
"""We use python numpy array instead of a list because of the below three reasons:

Less Memory
Fast
Convenient"""

import numpy as np
 
import time
import sys

S= range(1000)
print("array size ",sys.getsizeof(5)*len(S))
 
D= np.arange(1000)
print("numpy size ", D.size*D.itemsize)

import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print("array operation time ",(time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print("numpy operation time ",(time.time()-start)*1000)


array size  28000
numpy size  8000
array operation time  181.58197402954102
numpy operation time  48.30121994018555


In [21]:
# find the dimension of array

import numpy as np
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [23]:
# ones zeros and range

import numpy as np 
x = np.ones([2,2], dtype = int) 
print(x)

x = np.zeros((5,), dtype = np.int) 
print(x)

a = np.arange(24) 
print (a)

x = np.arange(10,20,2) 
print (x)

import numpy as np 
x = np.linspace(1,2,50) 
print (x)

[[1 1]
 [1 1]]
[0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[10 12 14 16 18]
[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]


In [23]:
# size and shape of the array

import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [24]:
# reshape

import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [25]:
# slice

import numpy as np
a=np.array([(8,9,3),(10,11,2),(12,13,15)])
print(a)
print(a[0:3,0:2])

[[ 8  9  3]
 [10 11  2]
 [12 13 15]]
[[ 8  9]
 [10 11]
 [12 13]]


In [11]:
import numpy as np
k = np.random.rand(2,3)
print (k)

[[0.33479036 0.00977801 0.02878925]
 [0.57694642 0.78073449 0.71904933]]


In [26]:
#Boolean indexing

a = np.arange(12).reshape(3, 4)
print (a)
rows_on = np.array([True, False, True])
a[rows_on , : ]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [29]:
# advanced slicing

import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:')
print (x) 
print ()

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print ('The corner elements of this array are:')
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [30]:
# min/max & std deviation

import numpy as np
 
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())
print()

a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))

1
3
6

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [21]:
# Vertical & Horizontal Stacking

import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print()
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [32]:
# broadcasting- The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a)
   
print ('Second array:' )
print (b) 
   
print ('First Array + Second Array' )
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
[1. 2. 3.]
First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [33]:
# sorting 

import numpy as np  
a = np.array([[3,7,2],[9,1,4]]) 

print ('Our array is:')
print (a) 
print ()

print ('Applying sort() function:') 
print (np.sort(a) )
print () 
  
print ('Sort along axis 0:' )
print (np.sort(a, axis = 0) )
print ()

# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 

print ('Our array is:' )
print (a)
print ()  

print ('Order by name:')
print (np.sort(a, order = 'name'))
print()

Our array is:
[[3 7 2]
 [9 1 4]]

Applying sort() function:
[[2 3 7]
 [1 4 9]]

Sort along axis 0:
[[3 1 2]
 [9 7 4]]

Our array is:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]

Order by name:
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]



In [49]:
# split hsplit vsplit

import numpy as np 
a = np.arange(16).reshape(4,4) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Horizontal splitting:') 
b = np.hsplit(a,2) 
print (b) 
print ()

print ('Vertical splitting:') 
b = np.vsplit(a,2) 
print (b) 

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]

Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [34]:
# Linear algebra

#dot product of 2 matrices
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print (np.dot(a,b))

print()

# vdot product of 2 matrices
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print (np.vdot(a,b))

print()

# inverse of a matrix
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x) 
print (y) 

print()

# determinant of a matrix
a = np.array([[1,2], [3,4]]) 
print (a)
print (np.linalg.det(a))
print()

b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (b) 
print (np.linalg.det(b))

[[37 40]
 [85 92]]

130

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]

[[1 2]
 [3 4]]
-2.0000000000000004

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
